import mongoose from "mongoose";
import RevenueEvent from "../models/revenueEventModel.js";
import { appendLedgerEntry } from "./ledgerService.js";

const D128 = (v) => mongoose.Types.Decimal128.fromString(String(v));

/**
 * Records one dollar-figure the platform itself earned (as opposed to
 * Trade.fees, which records what a user paid — same number, different
 * aggregation axis). Chains into the ledger alongside every other
 * financially-meaningful event, same pattern as trades/wallet transactions/
 * price history/pledges.
 */
export async function recordRevenueEvent({
  event_type,
  amount,
  talent_id,
  trade_id = null,
  buyer_id = null,
  seller_id = null,
  notes = null,
}) {
  const event = await RevenueEvent.create({
    event_type,
    amount: D128(amount),
    talent_id,
    trade_id,
    buyer_id,
    seller_id,
    notes,
  });
  await appendLedgerEntry("revenue_event", event._id, event.toObject());
  return event;
}

async function revenueByType(match) {
  const results = await RevenueEvent.aggregate([
    { $match: match },
    { $group: { _id: "$event_type", amount: { $sum: { $toDouble: "$amount" } }, count: { $sum: 1 } } },
  ]);
  return Object.fromEntries(results.map((r) => [r._id, { amount: +r.amount.toFixed(2), count: r.count }]));
}

/** Platform-wide revenue summary, optionally scoped to a date range. */
export async function getRevenueSummary(startDate, endDate) {
  const match = {};
  if (startDate || endDate) {
    match.createdAt = {};
    if (startDate) match.createdAt.$gte = new Date(startDate);
    if (endDate) match.createdAt.$lte = new Date(endDate);
  }

  const byType = await revenueByType(match);
  const breakdown = Object.entries(byType).map(([type, v]) => ({ type, amount: v.amount, count: v.count }));
  const totalRevenue = +breakdown.reduce((sum, b) => sum + b.amount, 0).toFixed(2);
  const eventCount = breakdown.reduce((sum, b) => sum + b.count, 0);

  return {
    totalRevenue,
    listingFees: byType.listing_fee?.amount || 0,
    transactionFees: byType.transaction_fee?.amount || 0,
    marketMakingSpreads: byType.market_making_spread?.amount || 0,
    eventCount,
    breakdown,
  };
}

/** Revenue generated by a single tradable asset (Talent IS the asset in this codebase — no separate Asset entity). */
export async function getAssetRevenue(assetId) {
  const byType = await revenueByType({ talent_id: new mongoose.Types.ObjectId(assetId) });
  return {
    assetId,
    totalRevenue: +Object.values(byType).reduce((sum, v) => sum + v.amount, 0).toFixed(2),
    listingFee: byType.listing_fee?.amount || 0,
    totalTransactionFees: byType.transaction_fee?.amount || 0,
    totalMarketMaking: byType.market_making_spread?.amount || 0,
    tradeCount: byType.transaction_fee?.count || 0,
  };
}

/** Revenue attributable to a talent (same underlying query as getAssetRevenue — kept as a separate named export to match the spec's two distinct call sites). */
export async function getTalentRevenue(talentId) {
  const byType = await revenueByType({ talent_id: new mongoose.Types.ObjectId(talentId) });
  return {
    talentId,
    listingFee: byType.listing_fee?.amount || 0,
    totalFeesGenerated: +Object.values(byType).reduce((sum, v) => sum + v.amount, 0).toFixed(2),
    tradeCount: byType.transaction_fee?.count || 0,
  };
}
